#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class FlipView;
                ref class Button;
                ref class TextBox;
                ref class ListView;
            }
        }
    }
}

namespace Facegallery
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::FlipView^ FlipImage;
        private: ::Windows::UI::Xaml::Controls::Button^ ImportBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ ExportBtn;
        private: ::Windows::UI::Xaml::Controls::TextBox^ tbtest;
        private: ::Windows::UI::Xaml::Controls::ListView^ ListItems;
    };
}

